# Generated by Django 3.0.6 on 2020-05-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_yorumlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='yorumlar',
            options={'ordering': ['-comment_date']},
        ),
    ]
